---
title: "Proyecto"
output: html_document
---
#### Exploración de los datos 

### Librerías

```{r}
# Load necessary libraries
library(arm)        # Regression modeling
library(corrplot)   # Correlation plots
library(dplyr)      # Data manipulation
library(ggplot2)    # Data visualization
library(readxl)     # Read Excel files
library(tidyverse)  # Collection of data science tools
library(tidyr)      # Tidying data
```

### Datos

```{r}
# Read data
data0 <- read_excel("~/Desktop/Maestría Estadistica/2024/II Ciclo/Modelo Mixtos/Proyecto final/data.xlsx")

# Select relevant data columns
data = data0[,-c(1,3:8)]

# Convert variables to factors
data$Parte = as.factor(data$Parte)
data$Epoca = as.factor(data$Epoca)
data$Clase = as.factor(data$Clase)
```

```{r}
# Aggregate 'Parte' into 'Seccion'
data$Seccion <- factor(
  ifelse(data$Parte %in% c("I1", "I2", "I3"), "Alta",
         ifelse(data$Parte %in% c("M1", "M2", "M3"), "Media", "Baja"))
)

# Aggregate 'Clase' into 'Conta'
data$Conta <- (
  ifelse(data$Clase %in% c("1", "2"), 0,
         ifelse(data$Clase %in% c("3", "4", "5"), 1, 0))
)
```

### Exploración

```{r}
# Descriptive analysis of the dependent variable
tabla_frecuencias <- table(data$ICA)
tabla_proporciones <- prop.table(tabla_frecuencias)
barplot(table(data$ICA), main="", xlab="Valor", ylab="Frecuencia", col="#A9C6E7")
```

```{r}
# Correlation plot
corrplot(cor(data[,-c(1,2,28,29,30)]), method = "square", type = "lower")
```

```{r}
# Convert ICA to factor and get the number of unique categories
data$ICA = as.factor(data$ICA)
num_categories <- length(unique(data$ICA))

# Create a color palette for the categories
formal_blue_palette <- colorRampPalette(c("#A9C6E7", "#6FA3F0", "#004B87", "#002A5C"))(num_categories)

# Function to create a bar plot using tidy evaluation
create_bar_plot <- function(x_var, x_label) {
  ggplot(data, aes(x = .data[[x_var]], fill = ICA)) +  # Use .data for tidy evaluation
    geom_bar(position = "fill", color = "black") +
    labs(title = "", x = x_label, y = "Proporción") +
    scale_y_continuous(labels = scales::percent_format()) +
    scale_fill_manual(values = formal_blue_palette) +
    theme_minimal() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank())
}

# Generate plots for each variable
plot_parte <- create_bar_plot("Parte", "Sección de la Cuenca")
plot_epoca <- create_bar_plot("Epoca", "Época")
plot_seccion <- create_bar_plot("Seccion", "Sección de la Cuenca")

# Display plots 
print(plot_parte)
print(plot_epoca)
print(plot_seccion)
```

```{r}
# Convert response variable to numeric
data$ICA = as.numeric(data$ICA)

# Standardize numeric variables
datos_est <- data %>% mutate(across(where(is.numeric) & (3:27), scale))

# Select a sample of variables
datos_grap = datos_est[, c(1:2, 8, 22, 27:30)]

# Convert the dataframe to long format for ggplot
datos_long <- datos_grap %>%
  pivot_longer(cols = 3:4) %>%
  janitor::clean_names()  # Clean column names

# Function to create correlation plots
create_correlation_plot <- function(color_var, title) {
  ggplot(datos_long, aes(x = value, y = ica, color = !!sym(color_var))) +  
    geom_point(alpha = 0.6) +
    geom_smooth(method = "lm", se = FALSE) +
    facet_wrap(~ name) +
    labs(title = title) +
    theme_minimal()
}

# Generate correlation plots for different color variables
plot_climate <- create_correlation_plot("clase", "Correlación de Variables con Calidad de Agua por Clase")
plot_interpretation <- create_correlation_plot("interpretacion_de_calidad", "Correlación de Variables con Calidad de Agua por Interpretación de Calidad")
plot_epoca <- create_correlation_plot("epoca", "Correlación de Variables con Calidad de Agua por Época Climática")
plot_parte <- create_correlation_plot("parte", "Correlación de Variables con Calidad de Agua por Parte de la Cuenca")
plot_seccion <- create_correlation_plot("seccion", "Correlación de Variables con Calidad de Agua por Sección de la Cuenca")

# Display plots 
print(plot_climate)
print(plot_interpretation)
print(plot_epoca)
print(plot_parte)
print(plot_seccion)
```

```{r}
# Function to create heatmap
create_heatmap <- function(x_var, title) {
  ggplot(datos_long, aes_string(x = x_var, y = "epoca", fill = "ica")) +
    geom_tile() +
    scale_fill_gradient(low = "lightblue", high = "darkblue") +
    labs(title = title,
         x = "Sección de la Cuenca",
         y = "Época",
         fill = "ICA") +
    theme_minimal()
}

# Generate heatmaps for 'parte' and 'seccion'
heatmap_parte <- create_heatmap("parte", "Heatmap del Índice de Calidad de Agua por Parte")
heatmap_seccion <- create_heatmap("seccion", "Heatmap del Índice de Calidad de Agua por Sección")

# Display heatmaps
print(heatmap_parte)
print(heatmap_seccion)
```

#### Modelos

### Librerías

```{r}
# Load necessary libraries
library(MASS)
library(MCMCglmm)
library(R2jags) 
library(dplyr)
library(leaps)
library(readxl) 
library(sp)  
load.module("dic")  
load.module("glm")  
```

### Selección de variables

```{r}
# Scale selected columns (3 to 26) in the dataset
data_aux <- data %>% mutate(across(c(3:26), ~ scale(., center = TRUE, scale = FALSE)))

# Remove specific columns from the scaled dataset
data_aux1 <- data_aux[, -c(28, 29)]

# Exclude the "ICA" variable from the dataset
variables <- data_aux1[, -which(names(data_aux1) == "ICA")]

# Define the outcome variable as "ICA"
outcome <- data_aux1$ICA

# Perform best subset selection for regression
out_1 <- regsubsets(ICA ~ ., data = data_aux1)

# Output the summary of the best subset selection
summary(out_1)

# Plot the results of the best subset selection
plot(out_1)

# Select variables using stepwise AIC method on a pooled linear model
modelo_seleccionado <- stepAIC(lm(ICA ~., data = data_aux1), direction = "both", trace = FALSE)

# Output the summary of the selected model
summary(modelo_seleccionado)
```

### Modelo 1: Pooling 

```{r}
# Define and configure the JAGS model
jags_model_code <- "
model {
  for (i in 1:n) {
    y[i] ~ dnorm(mu[i], tau.y)           # Likelihood: y follows a normal distribution
    mu[i] <- beta0 + beta1 * x1[i] + beta2 * x2[i]  # Linear predictor
    e.y[i] <- y[i] - mu[i]                # Residuals
  }
  beta0 ~ dnorm(0, 0.001)                 # Prior for intercept
  beta1 ~ dnorm(0, 0.001)                 # Prior for slope of x1
  beta2 ~ dnorm(0, 0.001)                 # Prior for slope of x2
  tau.y <- pow(sigma.y, -2)               # Precision parameter
  sigma.y ~ dunif(0, 100)                 # Prior for standard deviation
}"
writeLines(jags_model_code, con = "modelo_jags.bug")  # Save model code to file

# Prepare data for JAGS
data_jags <- list(
  y = data$ICA,                              # Response variable
  x1 = as.numeric(data$`Temp agua (°C)`),   # Predictor variable 1
  x2 = as.numeric(data$`P sol (mgPO/l)`),    # Predictor variable 2
  n = nrow(data)                             # Number of observations
)

# Run the JAGS model
jags_model_results <- jags(
  data = data_jags,
  inits = function() list(beta0 = rnorm(1), beta1 = rnorm(1), beta2 = rnorm(1), sigma.y = runif(1, 0, 100)),  # Initial values
  parameters.to.save = c("beta0", "beta1", "beta2", "sigma.y", "e.y"),   # Parameters to monitor
  model.file = "modelo_jags.bug",   # Model file
  n.iter = 3000,                    # Total iterations
  n.burnin = 1000,                  # Burn-in period
  n.thin = 2,                       # Thinning interval
  n.chains = 3                      # Number of chains
)
print(jags_model_results)             # Print results

# Calculate R² for pooling
SP_pooling <- jags_model_results$BUGSoutput$sims.list   # Extract simulations from the results
r_y_pooling <- 1 - mean(apply(SP_pooling$e.y, 1, var)) / var(data$ICA)   # Calculate R² for pooling
cat(paste("R² for pooling model:", round(r_y_pooling, 4)), "\n")
```

```{r}
# Load the devtools library
library(devtools)
# Install the CalvinBayes package from GitHub

devtools::install_github("rpruim/CalvinBayes")
library(CalvinBayes)

# Define the parameters to analyze
parameters <- c("beta0", "beta1", "beta2")

 # Generate and display diagnostic plots 
for (param in parameters) {
  diag_mcmc(as.mcmc(jags_model_results), parName = param)
}
```

### Modelo 2: No pooling 

```{r}
# Define the JAGS model with factors 'epoca' and 'parte'
jags_model_code <- "
model {
  for (i in 1:n) {
    y[i] ~ dnorm(mu[i], tau.y)                     # Likelihood: y follows a normal distribution
    mu[i] <- beta0 + beta1 * x1[i] + beta2 * x2[i] + alpha_epoca[epoca[i]] + alpha_parte[parte[i]]  # Linear predictor
    e.y[i] <- y[i] - mu[i]                          # Residuals
  }
  beta0 ~ dnorm(0, 0.001)                           # Prior for intercept
  beta1 ~ dnorm(0, 0.001)                           # Prior for slope of x1
  beta2 ~ dnorm(0, 0.001)                           # Prior for slope of x2
  
  # Priors for random effects associated with 'epoca'
  for (j in 1:J_epoca) {
    alpha_epoca[j] ~ dnorm(0, 0.001)
  }
  
  # Priors for random effects associated with 'parte'
  for (k in 1:K_parte) {
    alpha_parte[k] ~ dnorm(0, 0.001)
  }
  
  tau.y <- pow(sigma.y, -2)                         # Precision parameter
  sigma.y ~ dunif(0, 100)                           # Prior for standard deviation
}"
writeLines(jags_model_code, con = "modelo_jags.bug")  # Save model code to file

# Prepare data for JAGS
data_jags <- list(
  y = data$ICA,                                      # Response variable
  x1 = as.numeric(data$`Temp agua (°C)`),           # Predictor variable 1
  x2 = as.numeric(data$`P sol (mgPO/l)`),            # Predictor variable 2
  epoca = data$Epoca,                                # Factor for random effect 'epoca'
  parte = data$Parte,                                # Factor for random effect 'parte'
  n = nrow(data),                                    # Number of observations
  J_epoca = max(as.numeric(as.factor(data$Epoca))), # Number of levels in 'epoca'
  K_parte = max(as.numeric(as.factor(data$Parte)))   # Number of levels in 'parte'
)

# Run the JAGS model
jags_model_results <- jags(
  data = data_jags,
  inits = function() list(beta0 = rnorm(1), beta1 = rnorm(1), sigma.y = runif(1, 0, 100)),   # Initial values
  parameters.to.save = c("beta0", "beta1", "beta2", "sigma.y", "alpha_epoca", "alpha_parte", "e.y"),   # Parameters to monitor
  model.file = "modelo_jags.bug",                  # Model file path
  n.iter = 3000,                                   # Total iterations
  n.burnin = 1000,                                 # Burn-in period
  n.thin = 2,                                      # Thinning interval
  n.chains = 3                                     # Number of chains
)
print(jags_model_results)                           # Print results

# Calculate R² for non-pooling model
SP_npooling <- jags_model_results$BUGSoutput$sims.list   # Extract simulations from the results
r_y_npooling <- 1 - mean(apply(SP_npooling$e.y, 1, var)) / var(data$ICA)   # Calculate R² for non-pooling model
cat(paste("R² for pooling model:", round(r_y_npooling, 4)), "\n")
```

```{r}
# Define the parameters to analyze
parameters <- c("beta0", "beta1", "beta2", "alpha_epoca[1]", "alpha_epoca[2]", "alpha_epoca[3]", "alpha_parte[1]", "alpha_parte[2]", "alpha_parte[3]", "alpha_parte[4]", "alpha_parte[5]", "alpha_parte[6]", "alpha_parte[7]", "alpha_parte[8]", "alpha_parte[9]")

 # Generate and display diagnostic plots 
for (param in parameters) {
  diag_mcmc(as.mcmc(jags_model_results), parName = param)
}
```

### Modelo 3: Pooling parcial multinivel no anidado e intercepto variable

```{r}
# Define the JAGS model
jags_model_code <- "
model {
  for (i in 1:n) {
    # Likelihood
    y[i] ~ dnorm(mu[i], tau.y)
    mu[i] <- beta0 + beta1 * x1[i] + beta2 * x2[i] + alpha_epoca[epoca[i]] + alpha_parte[parte[i]]
    
    e.y[i]  <- y[i] - mu[i]  # Residuals
  }

  # Priors for fixed effects
  beta0 ~ dnorm(0, 0.001)
  beta1 ~ dnorm(0, 0.001)
  beta2 ~ dnorm(0, 0.001)
  
  # Priors for random effects
  for (j in 1:J_epoca) {
    alpha_epoca[j] ~ dnorm(0, tau.epoca)
    e.e[j]  <- alpha_epoca[j] - beta0  # Residuals for epoch
  }
  
  for (k in 1:K_parte) {
    alpha_parte[k] ~ dnorm(0, tau.parte)
    e.p[k]  <- alpha_parte[k] - beta0   # Residuals for part
  }

  # Priors for precisions
  tau.y <- pow(sigma.y, -2)
  tau.epoca <- pow(sigma.epoca, -2)
  tau.parte <- pow(sigma.parte, -2)

  sigma.y ~ dunif(0, 100)         # Uniform prior for sigma.y
  sigma.epoca ~ dunif(0, 100)     # Uniform prior for sigma.epoca
  sigma.parte ~ dunif(0, 100)      # Uniform prior for sigma.parte
}
"

# Specify the path to save the JAGS model file
jags_model_path <- "modelo_jags.bug"

# Write the model code to a file
writeLines(jags_model_code, con = jags_model_path)

# Create a list of data for JAGS
data_jags <- list(
  y = data$ICA,                  # Dependent variable
  x1 = as.numeric(data$`Temp agua (°C)`), # Convert to numeric vector
  x2 = as.numeric(data$`P sol (mgPO/l)`),
  epoca = data$Epoca,            # Epoch index
  parte = data$Parte,            # Part index
  n = nrow(data),                # Number of observations
  J_epoca = max(as.numeric(as.factor(data$Epoca))),   # Maximum epoch index
  K_parte = max(as.numeric(as.factor(data$Parte)))    # Number of levels in part
)

# Initial values function for JAGS model parameters
inits <- function() {
  list(
    beta0 = rnorm(1),
    beta1 = rnorm(1),
    alpha_epoca = rnorm(data_jags$J_epoca),
    alpha_parte = rnorm(data_jags$K_parte),
    sigma.y = runif(1, 0, 100),
    sigma.epoca = runif(1, 0, 100),
    sigma.parte = runif(1, 0, 100)
  )
}

# Parameters to monitor during the JAGS model run
params <- c("beta0", "beta1", "beta2", "alpha_epoca", "alpha_parte", "sigma.y", "sigma.epoca", "sigma.parte", "e.e", "e.p", "e.y")

# Load and run the JAGS model
jags_model_results <- jags(
  data = data_jags,
  inits = inits,
  parameters.to.save = params,
  model.file = jags_model_path,
  n.iter = 3000,       # Total number of iterations
  n.burnin = 1000,     # Number of burn-in iterations
  n.thin = 2,          # Thinning interval (sample every second iteration)
  n.chains = 3         # Number of chains to run
)

# Print summary of the results from the JAGS model
print(jags_model_results)

# Calculate R²
SP_model3 <- jags_model_results$BUGSoutput$sims.list   # Extract simulations from the results
r_y_model3 <- 1 - mean(apply(SP_model3$e.y, 1, var)) / var(data$ICA)   # Calculate R² 
cat(paste("R² for model 3:", round(r_y_model3, 4)), "\n")

# Extract posterior samples and calculate omega
posterior_samples <- jags_model_results$BUGSoutput$sims.list
omega_model3 <- pmin((apply(posterior_samples$e.y, 2, sd) / mean(posterior_samples$sigma.y))^2, 1)
cat("Omega:\n")
plot(
  omega_model3,
  type = "l", col = "blue", lwd = 2,
  main = "", xlab = "Index", ylab = "Omega"
)
```

```{r}
# Define the parameters to analyze
parameters <- c("beta0", "beta1", "beta2", "alpha_epoca[1]", "alpha_epoca[2]", "alpha_epoca[3]", "alpha_parte[1]", "alpha_parte[2]", "alpha_parte[3]", "alpha_parte[4]", "alpha_parte[5]", "alpha_parte[6]", "alpha_parte[7]", "alpha_parte[8]", "alpha_parte[9]")

 # Generate and display diagnostic plots 
for (param in parameters) {
  diag_mcmc(as.mcmc(jags_model_results), parName = param)
}
```


### Modelo 4: Pooling parcial multinivel con efectos aleatorios a nivel de pendientes 

```{r}
# Define the JAGS model
jags_model_code <- "
model {
  for (i in 1:n) {
    # Likelihood
    y[i] ~ dnorm(mu[i], tau.y)
    mu[i] <- beta0 + beta1[epoca[i]] * x1[i] + beta2[epoca[i]] * x2[i]
    e.y[i]  <- y[i] - mu[i]  # Residuals
  }

  # Priors for fixed effects
  beta0 ~ dnorm(0, 0.001)
  
  # Priors for precision of the likelihood
  tau.y <- pow(sigma.y, -2)
  sigma.y ~ dunif(0, 100)
  
  # Priors for random effects
  for (j in 1:J_epoca) {
    beta1[j] ~ dnorm(m1, t1)
    beta2[j] ~ dnorm(m2, t2)
  }
  
  # Hyperparameters for random effects
  m1 ~ dnorm(0, 0.0001)
  m2 ~ dnorm(0, 0.0001)
  
  t1 <- pow(s1, -2)
  s1 ~ dunif(0, 100)
  
  t2 <- pow(s2, -2)
  s2 ~ dunif(0, 100)
}
"

# Specify the path to save the JAGS model file
jags_model_path <- "modelo_jags.bug"

# Write the model code to a file
writeLines(jags_model_code, con = jags_model_path)

# Create a list of data for JAGS
data_jags <- list(
  y = data$ICA,                  # Dependent variable
  x1 = as.numeric(data$`Temp agua (°C)`), # Independent variable 1
  x2 = as.numeric(data$`P sol (mgPO/l)`), # Independent variable 2
  epoca = data$Epoca,            # Epoch index
  n = nrow(data),                # Number of observations
  J_epoca = max(as.numeric(as.factor(data$Epoca))) # Maximum epoch index
)

# Initial values function for JAGS model parameters
inits <- function() {
  list(
    sigma.y = runif(1, 0, 100),   # Initial value for sigma.y
    s1 = runif(1, 0, 100),        # Initial value for s1
    s2 = runif(1, 0, 100)         # Initial value for s2
  )
}

# Parameters to monitor during the JAGS model run
params <- c("beta0", "beta1", "beta2", "sigma.y", "s1", "s2", "m1", "m2", "e.y")

# Load and run the JAGS model
jags_model_results <- jags(
  data = data_jags,
  inits = inits,
  parameters.to.save = params,
  model.file = jags_model_path,
  n.iter = 10000,       # Total number of iterations
  n.burnin = 3000,     # Number of burn-in iterations
  n.thin = 4,          # Thinning interval (sample every second iteration)
  n.chains = 3         # Number of chains to run
)

# Print summary of the results from the JAGS model
print(jags_model_results)

# Calculate R²
SP_model4 <- jags_model_results$BUGSoutput$sims.list   # Extract simulations from the results
r_y_model4 <- 1 - mean(apply(SP_model4$e.y , 1, var)) / var(data$ICA)   # Calculate R² 
cat(paste("R² for model 4:", round(r_y_model4, 4)), "\n")

# Extract posterior samples and calculate omega
posterior_samples <- jags_model_results$BUGSoutput$sims.list
omega_model4 <- pmin((apply(posterior_samples$e.y, 2, sd) / mean(posterior_samples$sigma.y))^2, 1)
cat("Omega:\n")
plot(
  omega_model4,
  type = "l", col = "blue", lwd = 2,
  main = "", xlab = "Index", ylab = "Omega"
)
```

```{r}
# Define the parameters to analyze
parameters <- c("beta0", "beta1[1]", "beta1[2]", "beta1[3]", "beta2[1]", "beta2[2]", "beta2[3]")

 # Generate and display diagnostic plots 
for (param in parameters) {
  diag_mcmc(as.mcmc(jags_model_results), parName = param)
}
```


